<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
        	["code" => "AF", "name" => "Afghanistan", "active" => 0],
			["code" => "AX", "name" => "Aland Islands", "active" => 0],
			["code" => "AL", "name" => "Albania", "active" => 0],
			["code" => "DZ", "name" => "Algeria", "active" => 0],
			["code" => "AS", "name" => "American Samoa", "active" => 0],
			["code" => "AD", "name" => "Andorra", "active" => 0],
			["code" => "AO", "name" => "Angola", "active" => 0],
			["code" => "AI", "name" => "Anguilla", "active" => 0],
			["code" => "AQ", "name" => "Antarctica", "active" => 0],
			["code" => "AG", "name" => "Antigua and Barbuda", "active" => 0],
			["code" => "AR", "name" => "Argentina", "active" => 0],
			["code" => "AM", "name" => "Armenia", "active" => 0],
			["code" => "AW", "name" => "Aruba", "active" => 0],
			["code" => "AU", "name" => "Australia", "active" => 1],
			["code" => "AT", "name" => "Austria", "active" => 0],
			["code" => "AZ", "name" => "Azerbaijan", "active" => 0],
			["code" => "BS", "name" => "Bahamas", "active" => 0],
			["code" => "BH", "name" => "Bahrain", "active" => 0],
			["code" => "BD", "name" => "Bangladesh", "active" => 0],
			["code" => "BB", "name" => "Barbados", "active" => 0],
			["code" => "BY", "name" => "Belarus", "active" => 0],
			["code" => "BE", "name" => "Belgium", "active" => 0],
			["code" => "BZ", "name" => "Belize", "active" => 0],
			["code" => "BJ", "name" => "Benin", "active" => 0],
			["code" => "BM", "name" => "Bermuda", "active" => 0],
			["code" => "BT", "name" => "Bhutan", "active" => 0],
			["code" => "BO", "name" => "Bolivia", "active" => 0],
			["code" => "BA", "name" => "Bosnia and Herzegovina", "active" => 0],
			["code" => "BW", "name" => "Botswana", "active" => 0],
			["code" => "BV", "name" => "Bouvet Island", "active" => 0],
			["code" => "BR", "name" => "Brazil", "active" => 0],
			["code" => "VG", "name" => "British Virgin Islands", "active" => 0],
			["code" => "IO", "name" => "British Indian Ocean Territory", "active" => 0],
			["code" => "BN", "name" => "Brunei Darussalam", "active" => 0],
			["code" => "BG", "name" => "Bulgaria", "active" => 0],
			["code" => "BF", "name" => "Burkina Faso", "active" => 0],
			["code" => "BI", "name" => "Burundi", "active" => 0],
			["code" => "KH", "name" => "Cambodia", "active" => 0],
			["code" => "CM", "name" => "Cameroon", "active" => 0],
			["code" => "CA", "name" => "Canada", "active" => 0],
			["code" => "CV", "name" => "Cape Verde", "active" => 0],
			["code" => "KY", "name" => "Cayman Islands", "active" => 0],
			["code" => "CF", "name" => "Central African Republic", "active" => 0],
			["code" => "TD", "name" => "Chad", "active" => 0],
			["code" => "CL", "name" => "Chile", "active" => 0],
			["code" => "CN", "name" => "China", "active" => 0],
			["code" => "HK", "name" => "Hong Kong", "active" => 0],
			["code" => "MO", "name" => "Macao", "active" => 0],
			["code" => "CX", "name" => "Christmas Island", "active" => 0],
			["code" => "CC", "name" => "Cocos (Keeling) Islands", "active" => 0],
			["code" => "CO", "name" => "Colombia", "active" => 0],
			["code" => "KM", "name" => "Comoros", "active" => 0],
			["code" => "CG", "name" => "Congo (Brazzaville)", "active" => 0],
			["code" => "CD", "name" => "Congo, Democratic Republic of the ", "active" => 0],
			["code" => "CK", "name" => "Cook Islands", "active" => 0],
			["code" => "CR", "name" => "Costa Rica", "active" => 0],
			["code" => "CI", "name" => "Côte d'Ivoire", "active" => 0],
			["code" => "HR", "name" => "Croatia", "active" => 0],
			["code" => "CU", "name" => "Cuba", "active" => 0],
			["code" => "CY", "name" => "Cyprus", "active" => 0],
			["code" => "CZ", "name" => "Czech Republic", "active" => 0],
			["code" => "DK", "name" => "Denmark", "active" => 0],
			["code" => "DJ", "name" => "Djibouti", "active" => 0],
			["code" => "DM", "name" => "Dominica", "active" => 0],
			["code" => "DO", "name" => "Dominican Republic", "active" => 0],
			["code" => "EC", "name" => "Ecuador", "active" => 0],
			["code" => "EG", "name" => "Egypt", "active" => 0],
			["code" => "SV", "name" => "El Salvador", "active" => 0],
			["code" => "GQ", "name" => "Equatorial Guinea", "active" => 0],
			["code" => "ER", "name" => "Eritrea", "active" => 0],
			["code" => "EE", "name" => "Estonia", "active" => 0],
			["code" => "ET", "name" => "Ethiopia", "active" => 0],
			["code" => "FK", "name" => "Falkland Islands (Malvinas)", "active" => 0],
			["code" => "FO", "name" => "Faroe Islands, ", "active" => 0],
			["code" => "FJ", "name" => "Fiji", "active" => 0],
			["code" => "FI", "name" => "Finland", "active" => 0],
			["code" => "FR", "name" => "France", "active" => 0],
			["code" => "GF", "name" => "French Guiana", "active" => 0],
			["code" => "PF", "name" => "French Polynesia", "active" => 0],
			["code" => "TF", "name" => "French Southern Territories", "active" => 0],
			["code" => "GA", "name" => "Gabon", "active" => 0],
			["code" => "GM", "name" => "Gambia", "active" => 0],
			["code" => "GE", "name" => "Georgia", "active" => 0],
			["code" => "DE", "name" => "Germany", "active" => 0],
			["code" => "GH", "name" => "Ghana", "active" => 0],
			["code" => "GI", "name" => "Gibraltar", "active" => 0],
			["code" => "GR", "name" => "Greece", "active" => 0],
			["code" => "GL", "name" => "Greenland", "active" => 0],
			["code" => "GD", "name" => "Grenada", "active" => 0],
			["code" => "GP", "name" => "Guadeloupe", "active" => 0],
			["code" => "GU", "name" => "Guam", "active" => 0],
			["code" => "GT", "name" => "Guatemala", "active" => 0],
			["code" => "GG", "name" => "Guernsey", "active" => 0],
			["code" => "GN", "name" => "Guinea", "active" => 0],
			["code" => "GW", "name" => "Guinea-Bissau", "active" => 0],
			["code" => "GY", "name" => "Guyana", "active" => 0],
			["code" => "HT", "name" => "Haiti", "active" => 0],
			["code" => "HM", "name" => "Heard Island and Mcdonald Islands", "active" => 0],
			["code" => "VA", "name" => "Holy See (Vatican City State)", "active" => 0],
			["code" => "HN", "name" => "Honduras", "active" => 0],
			["code" => "HU", "name" => "Hungary", "active" => 0],
			["code" => "IS", "name" => "Iceland", "active" => 0],
			["code" => "IN", "name" => "India", "active" => 0],
			["code" => "ID", "name" => "Indonesia", "active" => 0],
			["code" => "IR", "name" => "Iran, Islamic Republic of", "active" => 0],
			["code" => "IQ", "name" => "Iraq", "active" => 0],
			["code" => "IE", "name" => "Ireland", "active" => 0],
			["code" => "IM", "name" => "Isle of Man", "active" => 0],
			["code" => "IL", "name" => "Israel", "active" => 0],
			["code" => "IT", "name" => "Italy", "active" => 0],
			["code" => "JM", "name" => "Jamaica", "active" => 0],
			["code" => "JP", "name" => "Japan", "active" => 0],
			["code" => "JE", "name" => "Jersey", "active" => 0],
			["code" => "JO", "name" => "Jordan", "active" => 0],
			["code" => "KZ", "name" => "Kazakhstan", "active" => 0],
			["code" => "KE", "name" => "Kenya", "active" => 0],
			["code" => "KI", "name" => "Kiribati", "active" => 0],
			["code" => "KP", "name" => "Korea, Democratic People's Republic of", "active" => 0],
			["code" => "KR", "name" => "Korea, Republic of", "active" => 0],
			["code" => "KW", "name" => "Kuwait", "active" => 0],
			["code" => "KG", "name" => "Kyrgyzstan", "active" => 0],
			["code" => "LA", "name" => "Lao PDR", "active" => 0],
			["code" => "LV", "name" => "Latvia", "active" => 0],
			["code" => "LB", "name" => "Lebanon", "active" => 0],
			["code" => "LS", "name" => "Lesotho", "active" => 0],
			["code" => "LR", "name" => "Liberia", "active" => 0],
			["code" => "LY", "name" => "Libya", "active" => 0],
			["code" => "LI", "name" => "Liechtenstein", "active" => 0],
			["code" => "LT", "name" => "Lithuania", "active" => 0],
			["code" => "LU", "name" => "Luxembourg", "active" => 0],
			["code" => "MK", "name" => "Macedonia, Republic of", "active" => 0],
			["code" => "MG", "name" => "Madagascar", "active" => 0],
			["code" => "MW", "name" => "Malawi", "active" => 0],
			["code" => "MY", "name" => "Malaysia", "active" => 0],
			["code" => "MV", "name" => "Maldives", "active" => 1],
			["code" => "ML", "name" => "Mali", "active" => 0],
			["code" => "MT", "name" => "Malta", "active" => 0],
			["code" => "MH", "name" => "Marshall Islands", "active" => 0],
			["code" => "MQ", "name" => "Martinique", "active" => 0],
			["code" => "MR", "name" => "Mauritania", "active" => 0],
			["code" => "MU", "name" => "Mauritius", "active" => 0],
			["code" => "YT", "name" => "Mayotte", "active" => 0],
			["code" => "MX", "name" => "Mexico", "active" => 0],
			["code" => "FM", "name" => "Micronesia, Federated States of", "active" => 0],
			["code" => "MD", "name" => "Moldova", "active" => 0],
			["code" => "MC", "name" => "Monaco", "active" => 0],
			["code" => "MN", "name" => "Mongolia", "active" => 0],
			["code" => "ME", "name" => "Montenegro", "active" => 0],
			["code" => "MS", "name" => "Montserrat", "active" => 0],
			["code" => "MA", "name" => "Morocco", "active" => 0],
			["code" => "MZ", "name" => "Mozambique", "active" => 0],
			["code" => "MM", "name" => "Myanmar", "active" => 0],
			["code" => "NA", "name" => "Namibia", "active" => 0],
			["code" => "NR", "name" => "Nauru", "active" => 0],
			["code" => "NP", "name" => "Nepal", "active" => 0],
			["code" => "NL", "name" => "Netherlands", "active" => 0],
			["code" => "AN", "name" => "Netherlands Antilles", "active" => 0],
			["code" => "NC", "name" => "New Caledonia", "active" => 0],
			["code" => "NZ", "name" => "New Zealand", "active" => 0],
			["code" => "NI", "name" => "Nicaragua", "active" => 0],
			["code" => "NE", "name" => "Niger", "active" => 0],
			["code" => "NG", "name" => "Nigeria", "active" => 0],
			["code" => "NU", "name" => "Niue", "active" => 0],
			["code" => "NF", "name" => "Norfolk Island", "active" => 0],
			["code" => "MP", "name" => "Northern Mariana Islands", "active" => 0],
			["code" => "NO", "name" => "Norway", "active" => 0],
			["code" => "OM", "name" => "Oman", "active" => 0],
			["code" => "PK", "name" => "Pakistan", "active" => 0],
			["code" => "PW", "name" => "Palau", "active" => 0],
			["code" => "PS", "name" => "Palestinian Territory, Occupied", "active" => 0],
			["code" => "PA", "name" => "Panama", "active" => 0],
			["code" => "PG", "name" => "Papua New Guinea", "active" => 0],
			["code" => "PY", "name" => "Paraguay", "active" => 0],
			["code" => "PE", "name" => "Peru", "active" => 0],
			["code" => "PH", "name" => "Philippines", "active" => 0],
			["code" => "PN", "name" => "Pitcairn", "active" => 0],
			["code" => "PL", "name" => "Poland", "active" => 0],
			["code" => "PT", "name" => "Portugal", "active" => 0],
			["code" => "PR", "name" => "Puerto Rico", "active" => 0],
			["code" => "QA", "name" => "Qatar", "active" => 0],
			["code" => "RE", "name" => "Réunion", "active" => 0],
			["code" => "RO", "name" => "Romania", "active" => 0],
			["code" => "RU", "name" => "Russia", "active" => 0],
			["code" => "RW", "name" => "Rwanda", "active" => 0],
			["code" => "BL", "name" => "Saint-Barthélemy", "active" => 0],
			["code" => "SH", "name" => "Saint Helena", "active" => 0],
			["code" => "KN", "name" => "Saint Kitts and Nevis", "active" => 0],
			["code" => "LC", "name" => "Saint Lucia", "active" => 0],
			["code" => "MF", "name" => "Saint-Martin (French part)", "active" => 0],
			["code" => "PM", "name" => "Saint Pierre and Miquelon", "active" => 0],
			["code" => "VC", "name" => "Saint Vincent and Grenadines", "active" => 0],
			["code" => "WS", "name" => "Samoa", "active" => 0],
			["code" => "SM", "name" => "San Marino", "active" => 0],
			["code" => "ST", "name" => "Sao Tome and Principe", "active" => 0],
			["code" => "SA", "name" => "Saudi Arabia", "active" => 0],
			["code" => "SN", "name" => "Senegal", "active" => 0],
			["code" => "RS", "name" => "Serbia", "active" => 0],
			["code" => "SC", "name" => "Seychelles", "active" => 0],
			["code" => "SL", "name" => "Sierra Leone", "active" => 0],
			["code" => "SG", "name" => "Singapore", "active" => 0],
			["code" => "SK", "name" => "Slovakia", "active" => 0],
			["code" => "SI", "name" => "Slovenia", "active" => 0],
			["code" => "SB", "name" => "Solomon Islands", "active" => 0],
			["code" => "SO", "name" => "Somalia", "active" => 0],
			["code" => "ZA", "name" => "South Africa", "active" => 0],
			["code" => "GS", "name" => "South Georgia and the South Sandwich Islands", "active" => 0],
			["code" => "SS", "name" => "South Sudan", "active" => 0],
			["code" => "ES", "name" => "Spain", "active" => 0],
			["code" => "LK", "name" => "Sri Lanka", "active" => 0],
			["code" => "SD", "name" => "Sudan", "active" => 0],
			["code" => "SR", "name" => "Suriname", "active" => 0],
			["code" => "SJ", "name" => "Svalbard and Jan Mayen Islands", "active" => 0],
			["code" => "SZ", "name" => "Swaziland", "active" => 0],
			["code" => "SE", "name" => "Sweden", "active" => 0],
			["code" => "CH", "name" => "Switzerland", "active" => 0],
			["code" => "SY", "name" => "Syrian Arab Republic (Syria)", "active" => 0],
			["code" => "TW", "name" => "Taiwan", "active" => 0],
			["code" => "TJ", "name" => "Tajikistan", "active" => 0],
			["code" => "TZ", "name" => "Tanzania, United Republic of", "active" => 0],
			["code" => "TH", "name" => "Thailand", "active" => 0],
			["code" => "TL", "name" => "Timor-Leste", "active" => 0],
			["code" => "TG", "name" => "Togo", "active" => 0],
			["code" => "TK", "name" => "Tokelau", "active" => 0],
			["code" => "TO", "name" => "Tonga", "active" => 0],
			["code" => "TT", "name" => "Trinidad and Tobago", "active" => 0],
			["code" => "TN", "name" => "Tunisia", "active" => 0],
			["code" => "TR", "name" => "Turkey", "active" => 0],
			["code" => "TM", "name" => "Turkmenistan", "active" => 0],
			["code" => "TC", "name" => "Turks and Caicos Islands", "active" => 0],
			["code" => "TV", "name" => "Tuvalu", "active" => 0],
			["code" => "UG", "name" => "Uganda", "active" => 0],
			["code" => "UA", "name" => "Ukraine", "active" => 0],
			["code" => "AE", "name" => "United Arab Emirates", "active" => 0],
			["code" => "GB", "name" => "United Kingdom", "active" => 0],
			["code" => "US", "name" => "United States of America", "active" => 0],
			["code" => "UM", "name" => "United States Minor Outlying Islands", "active" => 0],
			["code" => "UY", "name" => "Uruguay", "active" => 0],
			["code" => "UZ", "name" => "Uzbekistan", "active" => 0],
			["code" => "VU", "name" => "Vanuatu", "active" => 0],
			["code" => "VE", "name" => "Venezuela (Bolivarian Republic of)", "active" => 0],
			["code" => "VN", "name" => "Vietnam", "active" => 0],
			["code" => "VI", "name" => "Virgin Islands, US", "active" => 0],
			["code" => "WF", "name" => "Wallis and Futuna Islands", "active" => 0],
			["code" => "EH", "name" => "Western Sahara", "active" => 0],
			["code" => "YE", "name" => "Yemen", "active" => 0],
			["code" => "ZM", "name" => "Zambia", "active" => 0],
			["code" => "ZW", "name" => "Zimbabwe", "active" => 0]
        ]);
    }
}
